export enum MESSAGEBOX_ACTION_TYPES {
    SET_IS_ARTIFICIALINTELLIGENCE_OPEN = 'messagebox/SET_IS_ARTIFICIALINTELLIGENCE_OPEN',
    SET_IS_VITALS_OPEN = 'messagebox/SET_IS_VITALS_OPEN',
    SET_IS_POST_OPEN = 'messagebox/SET_IS_POST_OPEN',
    SET_IS_SOLARSYSTEM_OPEN = 'messagebox/SET_IS_SOLARSYSTEM_OPEN',
    SET_IS_PLANETS_OPEN = 'messagebox/SET_IS_PLANETS_OPEN',
    SET_IS_MOONS_OPEN = 'messagebox/SET_IS_MOONS_OPEN',
    SET_IS_MARAUDERS_OPEN = 'messagebox/SET_IS_MARAUDERS_OPEN',
    SET_IS_MESSAGES_OPEN = 'messagebox/SET_IS_MESSAGES_OPEN'
}